const dataMatchAll = {
  data1: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Dua kelompok (Dikotom)",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Normal",
    },
    uji: "2 independent sample t-test",
  },
  data2: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Dua kelompok (Dikotom)",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Tidak Normal",
    },
    uji: "Mann Whitney",
  },
  data3: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Dua kelompok (Dikotom)",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Kategorik",
      7: "",
    },
    uji: "Chi-square test",
  },
  data4: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Dua kelompok (Dikotom)",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Kategorik",
      7: "",
    },
    uji: "Fisher’s exact test (bila tidak memenuhi syarat chi-square)",
  },
  data5: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Lebih dari 2 kelompok (Polikotom)",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Normal",
    },
    uji: "one-way ANOVA",
  },
  data6: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Lebih dari 2 kelompok (Polikotom)",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Normal",
    },
    uji: "",
  },
  data7: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Lebih dari 2 kelompok (Polikotom)",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Tidak Normal",
    },
    uji: "Kruskal Wallis",
  },
  data8: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Lebih dari 2 kelompok (Polikotom)",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Kategorik",
      7: "",
    },
    uji: "Chi-square test",
  },
  data9: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Dua kelompok (Dikotom)",
      4: "Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Normal",
    },
    uji: "paired t-test",
  },
  data10: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Dua kelompok (Dikotom)",
      4: "Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Tidak Normal",
    },
    uji: "Wilcoxon signed ranks test",
  },
  data11: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Dua kelompok (Dikotom)",
      4: "Berpasangan",
      5: "Satu",
      6: "Kategorik",
      7: "",
    },
    uji: "McNemar",
  },
  data12: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Lebih dari 2 kelompok (Polikotom)",
      4: "Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Normal",
    },
    uji: "one-way repeated measures ANOVA",
  },
  data13: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Lebih dari 2 kelompok (Polikotom)",
      4: "Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Normal",
    },
    uji: "",
  },
  data14: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Lebih dari 2 kelompok (Polikotom)",
      4: "Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Tidak Normal",
    },
    uji: "Friedman test",
  },
  data15: {
    answer: {
      1: "Satu",
      2: "Kategorik",
      3: "Lebih dari 2 kelompok (Polikotom)",
      4: "Berpasangan",
      5: "Satu",
      6: "Kategorik",
      7: "",
    },
    uji: "Marginal Homogeneity atau Uji Wilcoxon",
  },
  data16: {
    answer: {
      1: "Satu",
      2: "Numerik",
      3: "",
      4: "",
      5: "Satu",
      6: "Numerik",
      7: "Normal",
    },
    uji: "Pearson atau regresi linear sederhana",
  },
  data17: {
    answer: {
      1: "Satu",
      2: "Numerik",
      3: "",
      4: "",
      5: "Satu",
      6: "Numerik",
      7: "Tidak Normal",
    },
    uji: "Spearman",
  },
  data18: {
    answer: {
      1: "Satu",
      2: "Numerik",
      3: "",
      4: "",
      5: "Satu",
      6: "Kategorik",
      7: "",
    },
    uji: "Regresi logistik sederhana",
  },
  data19: {
    answer: {
      1: "Dua atau lebih",
      2: "Kategorik",
      3: "dikotom/polikotom",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Normal",
    },
    uji: "factorial ANOVA",
  },
  data20: {
    answer: {
      1: "Dua atau lebih",
      2: "Kategorik",
      3: "dikotom/polikotom",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Numerik",
      7: "Tidak Normal",
    },
    uji: "ordered logistic regression",
  },
  data21: {
    answer: {
      1: "Dua atau lebih",
      2: "Kategorik",
      3: "dikotom/polikotom",
      4: "Tidak Berpasangan",
      5: "Satu",
      6: "Kategorik",
      7: "",
    },
    uji: "regresi logistik faktorial",
  },
  data22: {
    answer: {
      1: "Dua atau lebih",
      2: "Numerik",
      3: "",
      4: "",
      5: "Satu",
      6: "Numerik",
      7: "Normal",
    },
    uji: "multiple linear regression atau one-way ANCOVA",
  },
  data23: {
    answer: {
      1: "Dua atau lebih",
      2: "Numerik",
      3: "",
      4: "",
      5: "Satu",
      6: "Kategorik",
      7: "",
    },
    uji: "multiple logistic regression",
  },
  data24: {
    answer: {
      1: "Satu",
      2: "Numerik",
      3: "",
      4: "",
      5: "Dua atau lebih",
      6: "Numerik",
      7: "Normal",
    },
    uji: "one-way MANOVA",
  },
  data25: {
    answer: {
      1: "Dua atau lebih",
      2: "Numerik",
      3: "",
      4: "",
      5: "Dua atau lebih",
      6: "Numerik",
      7: "Normal",
    },
    uji: "one-way MANCOVA",
  },
};

export default dataMatchAll;